# -*- coding: utf-8 -*-
"""web-app-demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/rakesh4real/ocr.pytorch/blob/master/web_app_demo.ipynb
"""

from google.colab import output
output.serve_kernel_port_as_window(8084)

"""Run the above **and below** cells and then, click on link above 👆 `https://localhost:8084/` to see output (web-app) of code below👇 in new tab.


<br>
<br>


**Note:** The page will load when you see output like below in last cell. Reload the new tab if necessary.

```
INFO:     Uvicorn running on http://127.0.0.1:8084 (Press CTRL+C to quit)
INFO:     Started reloader process [147] using statreload
INFO:     Started server process [153]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```
"""

!git clone https://github.com/rakesh4real/ocr.pytorch.git

# Commented out IPython magic to ensure Python compatibility.
# %cd ocr.pytorch/checkpoints
!curl -O https://raw.githubusercontent.com/rakesh4real/ocr.pytorch/master/checkpoints/CTPN.pth
!curl -O https://raw.githubusercontent.com/rakesh4real/ocr.pytorch/master/checkpoints/CRNN-1010.pth
# %cd ..

!pip install fastapi
!pip install uvicorn
!pip install aiofiles
!pip install python-multipart

!python -m uvicorn main:app --reload --port 8084